// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Bwb7LxaexcPU0296qsMOqimFFNNYdn0',
    appId: '1:582794690383:web:497231a5ac573e41a18f3a',
    messagingSenderId: '582794690383',
    projectId: 'agora-meeting-rrom',
    authDomain: 'agora-meeting-rrom.firebaseapp.com',
    storageBucket: 'agora-meeting-rrom.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPGQ1Av5RdroFljOPruKuKWtKN1pYUoFI',
    appId: '1:582794690383:android:29cd50d7cb6d69d6a18f3a',
    messagingSenderId: '582794690383',
    projectId: 'agora-meeting-rrom',
    storageBucket: 'agora-meeting-rrom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfETU7V5_KNn1qudI2YRIyjpdOy--aHPY',
    appId: '1:582794690383:ios:45588c29d715de01a18f3a',
    messagingSenderId: '582794690383',
    projectId: 'agora-meeting-rrom',
    storageBucket: 'agora-meeting-rrom.firebasestorage.app',
    iosBundleId: 'com.example.agoraMeetingRoom',
  );

}